services:
  # app:
  #   build: .
  #   volumes:
  #     - .:/home/node/app
  #   ports:
  #     - 2106:2106
  db:
    build: ./.docker/mongodb
    image: mongodb_multi_nodes
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
